# -*- coding: utf-8 -*-
"""testes_de_precisasão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/MateusMurinelly/mch_lrng/blob/main/testes_de_precisas%C3%A3o.ipynb
"""

from sklearn.datasets import load_iris
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.naive_bayes import GaussianNB

iris = load_iris()

iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

iris_df

x = iris.data
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

len(x_train)

len(y_pred)

y_test

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)
scaler

model = Sequential()

model.add(Dense(units=10, activation='relu', input_dim=4))

#model.add(Dense(units=4,activation='relu'))

model.add(Dense(units=3, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(x_train,y_train, epochs=100, verbose=1)

y_pred = model.predict(x_test)
y_pred

precision = precision_score(y_test,y_pred,average='weighted')
precision

len(y_pred)







